// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxle_qJGCWv8xWzgGUk2E0M1wh2c0gnI',
    appId: '1:24056648348:web:64890f10ecf3357d10d359',
    messagingSenderId: '24056648348',
    projectId: 'elite-life-48631',
    authDomain: 'elite-life-48631.firebaseapp.com',
    storageBucket: 'elite-life-48631.firebasestorage.app',
    measurementId: 'G-0MQ8SXGCXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrsJnopmWS6z3ublm5G--qN1ijLbOqnQE',
    appId: '1:24056648348:android:516148fb0026a07110d359',
    messagingSenderId: '24056648348',
    projectId: 'elite-life-48631',
    storageBucket: 'elite-life-48631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJkyM32EfRC4CNUw9IJsHxs6WGkQbFC8',
    appId: '1:24056648348:ios:6b01611cf17b864010d359',
    messagingSenderId: '24056648348',
    projectId: 'elite-life-48631',
    storageBucket: 'elite-life-48631.firebasestorage.app',
    iosBundleId: 'com.example.mylife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJkyM32EfRC4CNUw9IJsHxs6WGkQbFC8',
    appId: '1:24056648348:ios:8ea531c8b217fef510d359',
    messagingSenderId: '24056648348',
    projectId: 'elite-life-48631',
    storageBucket: 'elite-life-48631.firebasestorage.app',
    iosBundleId: 'com.finvia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxle_qJGCWv8xWzgGUk2E0M1wh2c0gnI',
    appId: '1:24056648348:web:d2c7ef37db45cdb410d359',
    messagingSenderId: '24056648348',
    projectId: 'elite-life-48631',
    authDomain: 'elite-life-48631.firebaseapp.com',
    storageBucket: 'elite-life-48631.firebasestorage.app',
    measurementId: 'G-XM2L7N1X50',
  );
}
